server:
  port: 8090
spring:
  datasource:
    url:  jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: "local"

build:
  version: "3.0"

loans:
  message: "Welcome to XBank accounts loans local APIs"
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@xbank.com"
  onCallSupport:
    - (+62) 855-2222-3333
    - (+62) 837-4324-7868
